# Menus
menu:

# Customize
customize:
    logo:
        enabled: false
        width: 40
        height: 40
        url:
    profile:
        enabled: true # Whether to show profile bar
        avatar: /images/logo.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Oded Lazar
        author_title: I code during the day, and think about the bugs I created at night.
        location: Israel
        about: about-me
    highlight: github
    sidebar: right # sidebar position, options: left, right or leave it empty
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: https://github.com/odedlaz
        facebook: https://facebook.com/oded.blog
        linkedin: https://linkedin.com/in/odedlaz
        rss: https://oded.dev/atom.xml
        # twitter: https://twitter.com/odedlaz
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - tagcloud
    - category
    - links

# Search
search: true

# Comment
comment:
    disqus: # thoughts-data-bugs
    isso: # isso.oded.dev
    facebook: # enter app id
    gitment:
        # owner: odedlaz
        # repo: oded.dev.comments
        # client_id: c0d55076889ae2a8f33d
        # client_secret: i<3hummus

links:
   # Hexo: http://hexo.io
